//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMTargets.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TargetEntities : DbContext
    {
        public TargetEntities()
            : base("name=TargetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<CampaignManager> CampaignManagers { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_campaignbyManager_Result> sp_campaignbyManager(Nullable<int> managerid)
        {
            var manageridParameter = managerid.HasValue ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_campaignbyManager_Result>("sp_campaignbyManager", manageridParameter);
        }
    
        public virtual ObjectResult<sp_AgentsbyManager_Result> sp_AgentsbyManager(Nullable<int> managerid)
        {
            var manageridParameter = managerid.HasValue ?
                new ObjectParameter("managerid", managerid) :
                new ObjectParameter("managerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AgentsbyManager_Result>("sp_AgentsbyManager", manageridParameter);
        }
    }
}
